export enum MessageConstant {
  MESSAGES_QUEUED_URL_CHECK,
  MESSAGES_QUEUED_URL_CHECK_FALSE,
  CONFIG_EXTRACTOR_URL_CHECK,
  CONFIG_EXTRACTOR_WEB_PAGE_NOT_LOADED,
  CONFIG_EXTRACTOR_CONNECT_PAGE_LOADED,
  POPUP_GET_ERRORS,
  SOLACE_CONNECTION_FAILED,
  QUEUE_BROWSER_CONNECION_FAILED,
  CLUSTER_NOT_EXTRACTED,
  HOST_NOT_EXTRACTED,
  VPN_NOT_EXTRACTED,
  USERNAME_NOT_EXTRACTED,
  PASSWORD_NOT_EXTRACTED,
}

export enum ChromeMessageType {
  SOLACE,
  BACKGROUND,
  CONFIG_EXTRACTOR,
  POPUP,
}

export type ChromeMessage = {
  from: ChromeMessageType;
  to: ChromeMessageType;
  message: MessageConstant;
};
