name: Publish extension

on:
  release:

jobs:
  publish-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch release asset
        id: fetch-asset
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: 'sqve-v.*\.zip'
          regex: true

      - name: Upload to store
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: "*.zip"
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          glob: true
          publish: false # TODO delete for next version
