name: Publish extension

on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed

jobs:
  publish-extension:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch release asset
        id: fetch-asset
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: 'sqve-v.*\.zip'
          regex: true

      - name: Upload to Chrome extension store
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: "*.zip"
          extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          glob: true
          publish: true

      - name: Upload to Edge Add-ons
        uses: wdzeng/edge-addon@v2
        with:
          product-id: ${{ secrets.EDGE_PRODUCT_ID }}
          zip-path: "*.zip"
          api-key: ${{ secrets.EDGE_API_KEY }}
          client-id: ${{ secrets.EDGE_CLIENT_ID }}
